version: '3.9'

services:
  mysql:
    build: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_file:/var/lib/mysql
    networks:
      - test_net

  php-fpm:
    build: php-fpm
    container_name: php-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./api:/var/www/html/api
      - ./connection:/var/www/html/connection
      - ./class:/var/www/html/class
    networks:
      - test_net

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./index.html:/var/www/html/index.html
      - ./api:/var/www/html/api
      - ./connection:/var/www/html/connection
      - ./class:/var/www/html/class
    networks:
      - test_net

volumes:
  db_file:

networks:
  test_net:
    driver: bridge